exception: show message to reload system
Added a message that tells the user that they can press reset (or Z on their GameCube Controller) to force reload because users tended to just unplug their Wiis from power.

---------

Co-authored-by: DacoTaco <daco_65@hotmail.com>
Co-authored-by: Extrems <metaradil@gmail.com>